---
language: python
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
env:
  # run against latest version
  - ANSIBLE_VERSION=latest
  # run against minimal required version
  - ANSIBLE_VERSION=2.2.*

# Use the new container infrastructure
sudo: false

# Install pip
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible and dependencies
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible ansible-lint --upgrade; else pip install ansible=="$ANSIBLE_VERSION" ansible-lint --upgrade; fi
  - pip install mock

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=./tests/requirements/:../' >ansible.cfg

script:
  # Run ansible-lint
  - ansible-lint .

  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Unit tests
  - pytest

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/